[versions]
agp = "8.1.0"
appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
volley = "1.2.1"
junit = "4.13.2"
extJunit = "1.1.5"
espresso = "3.5.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
com-android-volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }